name: CD - Deploy Application Stack
on:
  push:
    branches:
      - deployment

jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Docker Compose
        run: |
          docker compose pull
          docker compose up -d
