name: Apply Terraform which triggers Ansible

on:
  push:
    branches:
      - infra_main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # - name: Import Existing Resources
      #   run: |
      #     terraform import google_compute_network.main projects/project-2-443816/global/networks/main-vpc || echo "Network already imported"
      #     terraform import google_compute_disk.additional_disk projects/project-2-443816/zones/us-east1-b/disks/my-disk || echo "Disk already imported"
      #     terraform import google_compute_subnetwork.main projects/project-2-443816/regions/us-east1/subnetworks/main-subnet || echo "Sub-Network already imported"
      #     terraform import google_compute_firewall.web_server_sg projects/project-2-443816/global/firewalls/web-server-sg || echo "Web Server already imported"
      #     terraform import google_compute_instance.web_server projects/project-2-443816/zones/us-east1-b/instances/web-server
           
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
