name: Terraform Validate

on:
  push:
    branches:
      - infra_features

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json  
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

        