name: Apply Terraform which triggers Ansible

on:
  push:
    branches:
      - infra_main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
