name: Terraform Plan and Cost Estimation

on:
  pull_request:
    branches:
      - infra_main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: InfraCost
        uses: infracost/infracost-action@v1
        with:
          path: infracost.json
