name: Terraform Plan and Cost Estimation

on:
  pull_request:
    branches:
      - infra_main

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud auth
      - name: Set up Google Cloud auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json  
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Setup Infracost
      - name: Setup Infracost
        uses: infracost/actions/setup@v3.0.1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Step 7: Generate Infracost cost estimate baseline
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      # Step 8: Generate Infracost diff
      - name: Generate Infracost diff
        run: |
          infracost diff --path=. \
                         --format=json \
                         --compare-to=/tmp/infracost-base.json \
                         --out-file=/tmp/infracost.json

      # Step 9: Post Infracost comment to PR
      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ secrets.GITHUB_TOKEN }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update

      # Step 10: Cleanup
      - name: Cleanup
        run: rm -f /tmp/account.json
